apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hospital-applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/jeniel/hospital.git
        revision: main   # <--- dito
        directories:
          - path: appointmentservice
          - path: hospi
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/jeniel/hospital.git
        path: '{{path}}'
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

