
name: Java CI with Maven
permissions:
  contents: write  # ✅ Allow push to repo
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: npm
    - name: Checkout code
      uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
         node-version: '18'   # or your preferred Node.js version
         cache: 'npm'

      # 3️⃣ Install dependencies
    - name: Install dependencies
      run: npm install

      # 4️⃣ Run tests (if any)
    - name: Run tests
      run: npm test

      # 5️⃣ Start the app (optional)
    - name: Start App
      run: npm start



    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/hospital:${{ github.sha }}

    - name: Install yq
      run: sudo wget -qO /usr/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 && sudo chmod +x /usr/bin/yq
